
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  analytics:
    staging:
      hubspot_hp:
        +materialized: view
        bind: false
        +schema: staging_hubspot_hp
      rds_application_prod:
        +materialized: view
        bind: false
        +schema: staging_rds_application_prod
      hubspot_milkshake:
        +materialized: view
        bind: false
        +schema: staging_hubspot_milkshake
      sage:
        +materialized: view
        bind: false
        +schema: staging_sage
      stg_ref:
        +materialized: view
        bind: false
        +schema: staging_stg_ref
      custom_sage:
        +materialized: view
        bind: false
        +schema: staging_custom_sage
      dialpad:  
        +materialized: view
        bind: false
        +schema: staging_dialpad
      greenhouse:  
        +materialized: view
        bind: false
        +schema: staging_greenhouse  
      google_analytics:  
        +materialized: view
        bind: false
        +schema: staging_google_analytics  
      taxpreparers:  
        +materialized: view
        bind: false
        +schema: staging_taxpreparers  
    elt:
      hubspot:
        +materialized: view
        bind: false
        +schema: elt
      rds_application_prod:
        +materialized: view
        bind: false
        +schema: elt
      sage:
        +materialized: view
        bind: false
        +schema: elt_sage
      taxpreparers:
        +materialized: view
        bind: false
        +schema: elt_taxpreparers
      greenhouse:
        +materialized: view
        bind: false
        +schema: elt_greenhouse
      hubspot_hp:
        +materialized: view
        bind: false
        +schema: elt_hubspot_hp
      hubspot_milkshake:
        +materialized: view
        bind: false
        +schema: elt_hubspot_milkshake
      google_analytics:
        +materialized: view
        bind: false
        +schema: elt_google_analytics
      custom_sage:
        +materialized: view
        bind: false
        +schema: elt_custom_sage
    int:
      hubspot:
        +materialized: view
        bind: false
        +schema: edw
      sage:
        +materialized: view
        bind: false
        +schema: edw  
      dialpad:  
        +materialized: view
        bind: false
        +schema: edw
      deals:  
        +materialized: view
        bind: false
        +schema: int_deals
      customers:  
        +materialized: view
        bind: false
        +schema: int_customers
      employees:  
        +materialized: view
        bind: false
        +schema: int_employees
      combined:  
        +materialized: view
        bind: false
        +schema: int_combined
      data_platform:  
        +materialized: view
        bind: false
        +schema: int_data_platform
    rpt:
      hubspot:
        +materialized: table
        +schema: edw
      sage:
        +materialized: table
        +schema: edw 
      dialpad:  
        +materialized: table
        +schema: edw
      admin:  
        +materialized: table
        +schema: rpt_admin
      compliance:  
        +materialized: table
        +schema: rpt_compliance
      executive:  
        +materialized: table
        +schema: rpt_executive
      fpa:  
        +materialized: table
        +schema: rpt_fpa
      hr:  
        +materialized: table
        +schema: rpt_hr
      marketing:  
        +materialized: table
        +schema: rpt_marketing
      ops:  
        +materialized: table
        +schema: rpt_ops
      sales:  
        +materialized: table
        +schema: rpt_sales
    ref:
      reference:
        +materialized: table
        +schema: ref



