select 
    fs.*,
    ads.active_stage_label,
    ads.active_stage_entered,
    ads.active_stage_id,
    d.deal_id as honeypot_deal_id,
    d.dealname,
    d.company_name As company_name_honeypot,
    d.credit_type,
    d.total_invoiced_amount,
    d.dynamic_gross_revenue,
    d.gross_revenue_from_credits,
    d.calculated_refund_amount,
    d.hs_analytics_latest_source,
    d.hs_analytics_latest_source_company,
    d.hs_analytics_latest_source_contact,
    d.hs_analytics_latest_source_data_1,
    d.hs_analytics_latest_source_data_1_company,
    d.hs_analytics_latest_source_data_1_contact,
    d.hs_analytics_latest_source_data_2,
    d.hs_analytics_latest_source_data_2_company,
    d.hs_analytics_latest_source_data_2_contact,
    d.hs_analytics_latest_source_timestamp,
    d.hs_analytics_latest_source_timestamp_contact,
    d.hs_analytics_source,
    d.hs_analytics_source_data_1,
    d.hs_analytics_source_data_2,
    d.hs_deal_stage_probability,
    d.tax_prep_status,
    d.assigned_tax_preparer,
    d.ambassador_type,
    d.utm_campaign,
    d.utm_content,
    d.utm_medium,
    d.utm_source,
    d.owner_id,
    d.number_of_associated_ambassadors,
    d.total_rpr_amount,
    d.latest_deal_bucket,
    d.original_deal_bucket,
    c.average_w2_employees_2019,
    c.average_w2_employees_2020,
    c.average_w2_employees_2021,
    CONCAT( o.first_name, CONCAT(' ', o.last_name)) as owner_full_name
from {{ ref('prep_hubspot_hp__deal_stage__flattened_stages')}} fs
LEFT JOIN {{ ref('stg_hubspot_hp_deals') }} d ON fs.deal_id = d.deal_id
LEFT JOIN {{ ref('stg_hubspot_hp_deal_company') }} dc ON d.deal_id = dc.deal_id and dc.type_id = 5
LEFT JOIN {{ ref('stg_hubspot_hp_company') }} c ON dc.company_id = c.company_id and dc.type_id = 5
LEFT JOIN {{ ref('prep_hubspot_hp__deal_stage__active_dealstage') }} ads on ads.deal_id = d.deal_id
LEFT JOIN {{ ref('stg_hubspot_hp_owner') }} o on o.owner_id = d.owner_id 