select 
 d.deal_id
, deal_pipeline_stage_id
, deal_pipeline_id
, owner_id
, dealname
, credit_type
, calculated_refund_amount
, total_invoiced_amount
, dynamic_gross_revenue
, gross_revenue_from_credits
, hs_analytics_latest_source
, hs_analytics_latest_source_company
, hs_analytics_latest_source_contact
, hs_analytics_latest_source_data_1
, hs_analytics_latest_source_data_1_company
, hs_analytics_latest_source_data_1_contact
, hs_analytics_latest_source_data_2
, hs_analytics_latest_source_data_2_company
, hs_analytics_latest_source_data_2_contact
, hs_analytics_latest_source_timestamp
, hs_analytics_latest_source_timestamp_contact
, hs_analytics_source
, hs_analytics_source_data_1
, hs_analytics_source_data_2
, hs_deal_stage_probability
, tax_prep_status
, sent_to_shell_law_tax_llc as assigned_tax_preparer
, ambassador_type
, n_941_x_upload_date
, statement_of_facts_received
, statement_of_facts_upload_date
, time_between_docs_sent_to_cpa_and_941_x_upload_date
, at_any_point_in_time_during_2020_or_2021_did_you_utilize_a_peo_professional_employer_organization_
, tax_attorney_rejected_date
, utm_campaign
, utm_content
, utm_medium
, utm_source
, number_of_associated_ambassadors
, total_rpr_amount
, invoice_signed_date
, original_deal_bucket
, latest_deal_bucket
, n_2020_erc_q_1_amount_formatted_
, n_2020_erc_q_2_amount_text_
, n_2020_erc_q_3_amount_text_
, n_2020_erc_q_4_amount_text_
, n_2021_erc_q_1_amount_text_
, n_2021_erc_q_2_amount_text_
, n_2021_erc_q_3_amount_text_
, n_2021_erc_q_4_amount_formatted_
, est_refund_amount_formatted_
, number_of_credits
, closedate
, csc_owner
, latest_deal_stage_before_closed_lost
, close_lost_categories_new_
, company_name
, legal_company_name
, active_stage_id
, active_stage_label
, active_stage_entered
, fs.date_entered_legacy_stage_invoice_signed
, fs.date_entered_legacy_stage_docs_sent_to_cpa
, fs.date_entered_legacy_stage_data_aggregation_started
, fs.date_entered_legacy_stage_confirmed_lead
, fs.date_entered_legacy_stage_initiated_document_upload
, fs.date_entered_legacy_stage_refund_received_finalized
, fs.date_entered_legacy_stage_closed_lost
, fs.date_entered_legacy_stage_refund_qualified
, fs.date_entered_legacy_stage_completed_document_upload
, fs.date_entered_legacy_stage_cpa_created_invoice
, fs.date_entered_legacy_stage_awaiting_refund
, fs.date_entered_legacy_stage_data_aggregation_complete

FROM {{ ref('stg_hubspot_hp_deal') }} d 
LEFT JOIN {{ ref('prep_hubspot_hp__deal_stage__active_dealstage') }} ads on ads.deal_id = d.deal_id
LEFT JOIN {{ ref('prep_hubspot_hp__deal_stage__flattened_stages')}} fs  ON fs.deal_id = d.deal_id