-- select * 
-- from {{ ref('int_honeypot_all_deals') }} hd
-- LEFT JOIN {{ ref('stg_hubspot_hp_deal_company') }} dc  
-- ON hd.deal_id = dc.deal_id and dc.type_id = 5
-- LEFT JOIN {{ ref('int_honeypot_companies') }} hc
-- ON dc.company_id = hc.company_id and dc.type_id = 5

select 
hd.deal_id
,hd.deal_pipeline_stage_id
,hd.deal_pipeline_id
,hd.owner_id
,hd.dealname
,hd.credit_type
,hd.calculated_refund_amount
,hd.total_invoiced_amount
,hd.dynamic_gross_revenue
,hd.gross_revenue_from_credits
,hd.hs_analytics_latest_source
,hd.hs_analytics_latest_source_company
,hd.hs_analytics_latest_source_contact
,hd.hs_analytics_latest_source_data_1
,hd.hs_analytics_latest_source_data_1_company
,hd.hs_analytics_latest_source_data_1_contact
,hd.hs_analytics_latest_source_data_2
,hd.hs_analytics_latest_source_data_2_company
,hd.hs_analytics_latest_source_data_2_contact
,hd.hs_analytics_latest_source_timestamp
,hd.hs_analytics_latest_source_timestamp_contact
,hd.hs_analytics_source
,hd.hs_analytics_source_data_1
,hd.hs_analytics_source_data_2
,hd.hs_deal_stage_probability
,hd.tax_prep_status
,hd.assigned_tax_preparer
,hd.ambassador_type
,hd.n_941_x_upload_date
,hd.statement_of_facts_received
,hd.statement_of_facts_upload_date
,hd.time_between_docs_sent_to_cpa_and_941_x_upload_date
,hd.at_any_point_in_time_during_2020_or_2021_did_you_utilize_a_peo_professional_employer_organization_
,hd.tax_attorney_rejected_date
,hd.utm_campaign
,hd.utm_content
,hd.utm_medium
,hd.utm_source
,hd.number_of_associated_ambassadors
,hd.total_rpr_amount
,hd.invoice_signed_date
,hd.original_deal_bucket
,hd.latest_deal_bucket
,hd.n_2020_erc_q_1_amount_formatted_
,hd.n_2020_erc_q_2_amount_text_
,hd.n_2020_erc_q_3_amount_text_
,hd.n_2020_erc_q_4_amount_text_
,hd.n_2021_erc_q_1_amount_text_
,hd.n_2021_erc_q_2_amount_text_
,hd.n_2021_erc_q_3_amount_text_
,hd.n_2021_erc_q_4_amount_formatted_
,hd.est_refund_amount_formatted_
,hd.number_of_credits
,hd.closedate
,hd.csc_owner
,hd.latest_deal_stage_before_closed_lost
,hd.close_lost_categories_new_
,hd.company_name
,hd.legal_company_name
,hd.active_stage_id
,hd.active_stage_label
,hd.active_stage_entered
,hd.date_entered_legacy_stage_invoice_signed
,hd.date_entered_legacy_stage_docs_sent_to_cpa
,hd.date_entered_legacy_stage_data_aggregation_started
,hd.date_entered_legacy_stage_confirmed_lead
,hd.date_entered_legacy_stage_initiated_document_upload
,hd.date_entered_legacy_stage_refund_received_finalized
,hd.date_entered_legacy_stage_closed_lost
,hd.date_entered_legacy_stage_refund_qualified
,hd.date_entered_legacy_stage_completed_document_upload
,hd.date_entered_legacy_stage_cpa_created_invoice
,hd.date_entered_legacy_stage_awaiting_refund
,hd.date_entered_legacy_stage_data_aggregation_complete
,hc.company_id
,hc.is_deleted
,hc.portal_id
,hc.activities_checkboxes
,hc.activities_yesno
,hc.address
,hc.address_2
,hc.ambassador_agent_name
,hc.ambassador_category
,hc.ambassador_owner
,hc.annual_taxes
,hc.annualrevenue
,hc.approxcompanyrevenue_app
,hc.approximate_company_revenue
,hc.are_you_a_tribe_or_tribal_enterprise_
,hc.asset_size
,hc.assign_company_owner_field
,hc.assigned_sdr
,hc.associated_ambassador_name
,hc.average_number_of_part_time_w_2_employees_2019
,hc.average_number_of_part_time_w_2_employees_2020
,hc.average_number_of_part_time_w_2_employees_2021
,hc.average_w2_employees_2019
,hc.average_w2_employees_2020
,hc.average_w2_employees_2021
,hc.bank_referral_name
,hc.banktech_ventures_affiliate
,hc.business_start_date
,hc.campaign_scratchpad
,hc.check_any_of_the_following_that_apply_even_if_you_did_not_ultimately_use_or_fully_implement_it_in_
,hc.check_any_of_the_following_that_delayed_disrupted_or_negatively_impacted_your_business_as_a_result
,hc.city
,hc.cmc_tid
,hc.company_domain_name_com_format_
,hc.company_domain_name_format_field_
,hc.company_tax_id
,hc.company_type
,hc.contact_first_name
,hc.contact_last_name
,hc.contact_phone_number
,hc.cos_rid
,hc.country
,hc.covid_impact_category_from_app_
,hc.covid_impact_description
,hc.created_via_app_innovationrefunds_com
,hc.createdate
,hc.date_completed_section_a
,hc.date_completed_section_b
,hc.days_to_close
,hc.dba_name
,hc.describe_how_covid_has_negatively_impacted_the_business_or_changed_how_it_operates_since_2019_be_a
,hc.description
,hc.do_you_provide_healthcare_for_your_employees_
,hc.does_your_company_or_its_partners_have_80_or_more_ownership_in_any_other_businesses_
,hc.domain
,hc.dropbox_folder_name_not_path_
,hc.engagements_last_meeting_booked
,hc.entity_app
,hc.entity_filing_type
,hc.entity_type
,hc.erc_code_field
,hc.erc_dropbox_path
,hc.erc_dropbox_upload_url
,hc.erc_dropbox_url
,hc.erc_unqualified
,hc.erca_application_link
,hc.erca_authorization_disclosure_signed_date
,hc.erca_id
,hc.extension
,hc.facebook_company_page
,hc.family_on_payroll
,hc.family_on_payroll_yesno
,hc.first_contact_createdate
,hc.first_conversion_date
,hc.first_conversion_event_name
,hc.first_deal_created_date
,hc.firstname
,hc.form_tag
,hc.founded_year
,hc.graylisted_company_
,hc.growth_source
,hc.growth_source_1
,hc.growth_source_2
,hc.growth_source_3
,hc.hashed_email
,hc.have_you_accepted_funds_from_either_a_ppp_or_ppp_2_paycheck_protection_program_
,hc.have_you_qualified_for_and_claimed_any_federal_government_incentives_or_tax_credits_within_the_past
,hc.headquarters_location
,hc.how_did_you_hear_about_us_
,hc.how_do_you_plan_to_use_the_advance_
,hc.how_do_you_want_to_handle_repayment_
,hc.how_many_family_members_on_payroll_in_2020_and_2021_
,hc.how_much_of_your_refund_do_you_want_advanced_
,hc.howdidyouhearaboutus_app
,hc.hs_additional_domains
,hc.hs_all_accessible_team_ids
,hc.hs_all_owner_ids
,hc.hs_all_team_ids
,hc.hs_analytics_first_timestamp
,hc.hs_analytics_first_touch_converting_campaign
,hc.hs_analytics_first_visit_timestamp
,hc.hs_analytics_last_timestamp
,hc.hs_analytics_last_touch_converting_campaign
,hc.hs_analytics_last_visit_timestamp
,hc.hs_analytics_num_page_views
,hc.hs_analytics_num_visits
,hc.hs_annual_revenue_currency_code
,hc.hs_avatar_filemanager_key
,hc.hs_created_by_user_id
,hc.hs_date_entered_62526260
,hc.hs_date_entered_customer
,hc.hs_date_entered_lead
,hc.hs_date_entered_opportunity
,hc.hs_date_entered_salesqualifiedlead
,hc.hs_date_entered_subscriber
,hc.hs_date_exited_lead
,hc.hs_date_exited_opportunity
,hc.hs_date_exited_salesqualifiedlead
,hc.hs_date_exited_subscriber
,hc.hs_is_target_account
,hc.hs_last_booked_meeting_date
,hc.hs_last_logged_call_date
,hc.hs_last_open_task_date
,hc.hs_last_sales_activity_date
,hc.hs_last_sales_activity_timestamp
,hc.hs_last_sales_activity_type
,hc.hs_lastmodifieddate
,hc.hs_latest_meeting_activity
,hc.hs_lead_status
,hc.hs_merged_object_ids
,hc.hs_num_blockers
,hc.hs_num_child_companies
,hc.hs_num_contacts_with_buying_roles
,hc.hs_num_decision_makers
,hc.hs_num_open_deals
,hc.hs_object_id
,hc.hs_pinned_engagement_id
,hc.hs_pipeline
,hc.hs_predictivecontactscore_v_2
,hc.hs_sales_email_last_replied
,hc.hs_target_account_probability
,hc.hs_time_in_62526260
,hc.hs_time_in_customer
,hc.hs_time_in_lead
,hc.hs_time_in_opportunity
,hc.hs_time_in_salesqualifiedlead
,hc.hs_time_in_subscriber
,hc.hs_total_deal_value
,hc.hs_updated_by_user_id
,hc.hs_user_ids_of_all_notification_followers
,hc.hs_user_ids_of_all_notification_unfollowers
,hc.hs_user_ids_of_all_owners
,hc.hubspot_owner_assigneddate
,hc.hubspot_owner_id
,hc.hubspot_team_id
,hc.i_agree_to_a_href_https_qualify_innovationrefunds_com_terms_target_blank_terms_and_conditio
,hc.if_other
,hc.impacted_by_covid_yes_no_
,hc.industry
,hc.industry_from_app_
,hc.industry_ir_
,hc.initial_qualification_score
,hc.initiative_campaign_id
,hc.intake_email
,hc.intake_form_section_progress
,hc.is_public
,hc.job_role
,hc.job_title_google_form
,hc.job_title_ws_
,hc.lead_source
,hc.lifecyclestage
,hc.linkedin_company_page
,hc.linkedinbio
,hc.majority_owner
,hc.milkshake_companyid
,hc.milkshake_temp_marker
,hc.n_6_sense_account_buying_stage
,hc.n_6_sense_account_intent_score
,hc.n_6_sense_account_profile_fit
,hc.n_6_sense_account_reach_score
,hc.n_6_sense_employee_count_est_
,hc.n_6_sense_employee_range
,hc.n_6_sense_industry
,hc.n_6_sense_naics_code
,hc.n_6_sense_phone_company_
,hc.n_6_sense_sic_code
,hc.name
,hc.notes_last_contacted
,hc.notes_last_updated
,hc.notes_next_activity_date
,hc.num_associated_contacts
,hc.num_associated_deals
,hc.num_contacted_notes
,hc.num_conversion_events
,hc.num_notes
,hc.number_of_associated_closed_lost_deals
,hc.number_of_associated_open_deals
,hc.number_of_invoice_signed_deals
,hc.number_of_ppp_loans
,hc.number_of_r_e_deals_pending_creation
,hc.numberofemployees
,hc.opt_out_direct_mail
,hc.over_the_last_4_years_has_the_business_developed_designed_evaluated_enhanced_or_improved_any_com
,hc.owner_assignment_source
,hc.parent_to_be_associated_to_this_ambassador_if_applicable_
,hc.partner_referral_source_channel
,hc.pertaining_to_the_partners_in_your_company_other_than_your_spouse_have_there_been_any_immediate_f
,hc.phone
,hc.please_specify_which_incentives_or_credits_
,hc.ppp_amount_1
,hc.ppp_amount_2
,hc.ppp_date_1
,hc.ppp_date_2
,hc.ppp_forgiveness_1
,hc.ppp_forgiveness_2
,hc.ppp_funds_accepted_yesno
,hc.qualification_score
,hc.qualify_company_
,hc.quarterly_impact
,hc.quarterly_impact_from_app_
,hc.random
,hc.re_dropbox_url
,hc.re_unqualified
,hc.recent_closed_lost_category
,hc.recent_conversion_date
,hc.recent_conversion_event_name
,hc.recent_deal_amount
,hc.recent_deal_close_date
,hc.recent_deal_closed_lost_date
,hc.reengaged_deal_creation
,hc.reengaged_deal_owner
,hc.referred_by_
,hc.revive_reassignment_date
,hc.sdr_assigned_date
,hc.sdr_handoff
,hc.section_a_complete
,hc.section_b_complete
,hc.section_c_complete
,hc.section_d_complete
,hc.should_this_be_a_parent_ambassador_
,hc.sold_business_recently
,hc.state
,hc.state_dropdown
,hc.sub_4_qs
,hc.submission_idempotent_id
,hc.submitted_form_cloned_
,hc.submitted_via_intake_form
,hc.tax_preparer_type
,hc.temp_email
,hc.temp_first_name
,hc.temp_last_name
,hc.temp_phone_number
,hc.time_from_create_date
,hc.timezone
,hc.today_s_date
,hc.total_employees
,hc.total_ft_w_2_employees
,hc.total_money_raised
,hc.total_revenue
,hc.twitterhandle
,hc.type
,hc.utm_campaign_first_touch
,hc.utm_content_first_touch
,hc.utm_medium_first_touch
,hc.utm_source_first_touch
,hc.utm_term
,hc.utm_term_first_touch
,hc.utm_variant
,hc.web_technologies
,hc.website
,hc.what_is_your_role_or_job_title_
,hc.which_channel_news
,hc.which_channel_podcast
,hc.which_channel_radio
,hc.which_channel_siriusxm
,hc.which_channel_social_media
,hc.which_channel_sports
,hc.which_channel_tv
,hc.which_form_was_submitted_
,hc.which_siriusxm_channel_
,hc.whichchannel_app
,hc.years_in_business
,hc.zip
from {{ ref('int_honeypot_all_deals') }} hd
LEFT JOIN {{ ref('stg_hubspot_hp_deal_company') }} dc  
ON hd.deal_id = dc.deal_id and dc.type_id = 5
LEFT JOIN {{ ref('int_honeypot_companies') }} hc
ON dc.company_id = hc.company_id and dc.type_id = 5