select
    id
    ,property_invoice_signed_date               as invoice_signed_date
    ,property_assigned_collection_agent         as assigned_collection_agent
    ,property_csc_owner                         as csc_owner
    ,property_invoiced_amount                   as invoiced_amount
    ,property_check_amount                      as check_amount
    ,property_detailed_name                     as detailed_name
    ,property_hs_all_accessible_team_ids        as hs_all_accessible_team_ids
    ,property_associated_deal_name              as associated_deal_name
    ,property_hs_updated_by_user_id             as hs_updated_by_user_id
    ,property_associated_company_id             as associated_company_id
    ,property_hs_created_by_user_id             as hs_created_by_user_id
    ,property_dropbox_folder_path               as dropbox_folder_path
    ,property_estimated_refund_amount           as estimated_refund_amount
    ,property_hs_lastmodifieddate               as hs_lastmodifieddate
    ,property_irs_check_date                    as irs_check_date
    ,property_deal_stage                        as deal_stage
    ,property_hs_object_id                      as hs_object_id
    ,property_hs_createdate                     as hs_createdate
    ,property_associated_company_name           as associated_company_name
    ,property_hs_user_ids_of_all_owners         as hs_user_ids_of_all_owners
    ,property_est_ir_revenue_formatted_         as est_ir_revenue_formatted_
    ,property_invoice_sent_date                 as invoice_sent_date
    ,property_assigned_rac                      as assigned_rac
    ,property_file_url                          as file_url
    ,property_confirmed_date                    as confirmed_date
    ,property_irs_actual_refund_amount          as irs_actual_refund_amount
    ,property_irs_status                        as irs_status
    ,property_irs_issue_date                    as irs_issue_date
    ,property_confirmed_by_ir_date              as confirmed_by_ir_date
    ,property_description                       as description
    ,property_irs_issue_category                as irs_issue_category
    ,property_irs_issue_description             as irs_issue_description
    ,property_irs_issue_resolved_date           as irs_issue_resolved_date
    ,property_mail_tracking_id                  as mail_tracking_id
    ,property_gross_pay                         as gross_pay
    ,property_associated_deal_id                as associated_deal_id
    ,property_information_gathering_date        as information_gathering_date
    ,property_company_fein                      as company_fein
    ,property_city                              as city
    ,property_address_street_number_suite_or_room_number_ as address_street_number_suite_or_room_number_
    ,property_month_1_day_7                     as month_1_day_7
    ,property_month_1_day_21                    as month_1_day_21
    ,property_month_1_day_15                    as month_1_day_15
    ,property_month_1_day_29                    as month_1_day_29
    ,property_month_1_day_2                     as month_1_day_2
    ,property_month_1_day_30                    as month_1_day_30
    ,property_month_1_day_6                     as month_1_day_6
    ,property_month_2_day_14                    as month_2_day_14
    ,property_month_1_day_16                    as month_1_day_16
    ,property_month_1_day_9                     as month_1_day_9
    ,property_month_1_day_23                    as month_1_day_23
    ,property_month_1_day_8                     as month_1_day_8
    ,property_month_1_day_22                    as month_1_day_22
    ,property_change_in_qualifying_credit_amount_reason as change_in_qualifying_credit_amount_reason
    ,property_month_1_day_10                    as month_1_day_10
    ,property_month_1_day_24                    as month_1_day_24
    ,property_month_2_day_16                    as month_2_day_16
    ,property_month_2_day_13                    as month_2_day_13
    ,property_month_1_day_3                     as month_1_day_3
    ,property_month_2_day_15                    as month_2_day_15
    ,property_month_1_day_17                    as month_1_day_17
    ,property_month_2_day_1                     as month_2_day_1
    ,property_month_1_day_19                    as month_1_day_19
    ,property_month_1_day_31                    as month_1_day_31
    ,property_month_2_day_12                    as month_2_day_12
    ,property_month_1_day_1                     as month_1_day_1
    ,property_month_2_day_10                    as month_2_day_10
    ,property_month_1_day_28                    as month_1_day_28
    ,property_month_1_day_5                     as month_1_day_5
    ,property_month_1_day_20                    as month_1_day_20
    ,property_month_1_day_25                    as month_1_day_25
    ,property_month_1_day_27                    as month_1_day_27
    ,property_month_1_day_13                    as month_1_day_13
    ,property_month_1_day_14                    as month_1_day_14
    ,property_month_2_day_11                    as month_2_day_11
    ,property_order_number                      as order_number
    ,property_pending_review_date               as pending_review_date
    ,property_quarter                           as quarter
    ,property_name_amount                       as name_amount
    ,property_status                            as status
    ,property_name                              as name
    ,property_payment_received_date             as payment_received_date
    ,property_n_50_payment                      as n_50_payment
    ,property_tax_attorney_monitoring_status    as tax_attorney_monitoring_status
    ,property_tax_attorney_monitoring           as tax_attorney_monitoring
    ,property_refund_mail_date                  as refund_mail_date
    ,property_refund_mail_date_population       as refund_mail_date_population
    ,property_rac_status                        as rac_status
    ,property_promised_to_pay_date              as promised_to_pay_date
    ,property_previously_claimed_date           as previously_claimed_date
    ,property_rac_status_received_time_stamp    as rac_status_received_time_stamp
    ,property_rac_status_attempted_contact_unsuccessful_time_stamp as rac_status_attempted_contact_unsuccessful_time_stamp
    ,property_rac_status_not_received_time_stamp as rac_status_not_received_time_stamp
    ,property_tax_transcript_received           as tax_transcript_received
    ,property_n_2848_status                     as n_2848_status
    ,property_tax_transcript_sent               as tax_transcript_sent
    ,property_previous_quarter_gross_pay        as previous_quarter_gross_pay
    ,property_number_of_employees               as number_of_employees
    ,property_previous_quarter_revenue          as previous_quarter_revenue
    ,property_previous_quarter_number_of_employees as previous_quarter_number_of_employees
    ,property_revenue                           as revenue
    ,property_n_3911_time_stamp                 as n_3911_time_stamp
    ,property_qualifying_wages                  as qualifying_wages
    ,property_n_8821_b_time_stamp               as n_8821_b_time_stamp
    ,property_quarter_new                       as quarter_new
    ,property_taxliabilitymonth_1               as taxliabilitymonth_1
    ,property_month_3_day_18                    as month_3_day_18
    ,property_n_5_a_taxable_social_security_wages as n_5_a_taxable_social_security_wages
    ,property_month_3_day_2                     as month_3_day_2
    ,property_state                             as state
    ,property_month_3_day_30                    as month_3_day_30
    ,property_name_not_your_trade_name_         as name_not_your_trade_name_
    ,property_month_2_day_28                    as month_2_day_28
    ,property_month_3_day_25                    as month_3_day_25
    ,property_month_3_day_11                    as month_3_day_11
    ,property_requires_schd_b                   as requires_schd_b
    ,property_n_11_b_nonrefundable_portion_of_credit_for_qualified_sick_and_family_leave_wages_from_worksheet_1_11_b as n_11_b_nonrefundable_portion_of_credit_for_qualified_sick_and_family_leave_wages_from_worksheet_1_11_b
    ,property_month_2_day_20                    as month_2_day_20
    ,property_month_3_day_17                    as month_3_day_17
    ,property_month_3_day_23                    as month_3_day_23
    ,property_month_3_day_6                     as month_3_day_6
    ,property_month_2_day_4                     as month_2_day_4
    ,property_month_2_day_6                     as month_2_day_6
    ,property_month_3_day_3                     as month_3_day_3
    ,property_month_3_day_15                    as month_3_day_15
    ,property_month_2_day_19                    as month_2_day_19
    ,property_month_3_day_19                    as month_3_day_19
    ,property_month_3_day_5                     as month_3_day_5
    ,property_month_2_day_5                     as month_2_day_5
    ,property_month_3_day_9                     as month_3_day_9
    ,property_month_2_day_21                    as month_2_day_21
    ,property_month_3_day_4                     as month_3_day_4
    ,property_month_2_day_7                     as month_2_day_7
    ,property_month_2_day_30                    as month_2_day_30
    ,property_month_2_day_27                    as month_2_day_27
    ,property_month_3_day_24                    as month_3_day_24
    ,property_month_3_day_26                    as month_3_day_26
    ,property_month_3_day_12                    as month_3_day_12
    ,property_month_2_day_29                    as month_2_day_29
    ,property_month_2_day_22                    as month_2_day_22
    ,property_month_2_day_8                     as month_2_day_8
    ,property_month_3_day_31                    as month_3_day_31
    ,property_month_3_day_10                    as month_3_day_10
    ,property_month_2_day_26                    as month_2_day_26
    ,property_n_5_b_taxable_social_security_tips as n_5_b_taxable_social_security_tips
    ,property_month_3_day_28                    as month_3_day_28
    ,property_month_2_day_3                     as month_2_day_3
    ,property_month_2_day_25                    as month_2_day_25
    ,property_month_3_day_16                    as month_3_day_16
    ,property_month_2_day_18                    as month_2_day_18
    ,property_month_3_day_7                     as month_3_day_7
    ,property_month_3_day_20                    as month_3_day_20
    ,property_month_2_day_17                    as month_2_day_17
    ,property_month_2_day_24                    as month_2_day_24
    ,property_month_3_day_8                     as month_3_day_8
    ,property_month_3_day_29                    as month_3_day_29
    ,property_month_3_day_22                    as month_3_day_22
    ,property_month_3_day_1                     as month_3_day_1
    ,property_month_2_day_31                    as month_2_day_31
    ,property_month_3_day_14                    as month_3_day_14
    ,property_month_2_day_2                     as month_2_day_2
    ,property_tax_preparer_email                as tax_preparer_email
    ,property_month_3_day_21                    as month_3_day_21
    ,property_month_2_day_9                     as month_2_day_9
    ,property_upload_id_for_forms               as upload_id_for_forms
    ,property_year                              as year
    ,property_file_upload                       as file_upload
    ,property_upload_date                       as upload_date
    ,property_written_off_date                  as written_off_date
    ,property_upload_required_date              as upload_required_date
    ,property_theodo_file_name                  as theodo_file_name
    ,property_taxliabilityquarter               as taxliabilityquarter
    ,property_trade_name_if_any_                as trade_name_if_any_
    ,property_taxliabilitymonth_2               as taxliabilitymonth_2
    ,property_zip_code                          as zip_code
    ,property_taxliabilitymonth_3               as taxliabilitymonth_3
    ,property_month_1_day_4                     as month_1_day_4
    ,property_month_1_day_12                    as month_1_day_12
    ,property_month_1_day_26                    as month_1_day_26
    ,property_month_2_day_23                    as month_2_day_23
    ,property_month_1_day_11                    as month_1_day_11
    ,property_month_3_day_27                    as month_3_day_27
    ,property_month_3_day_13                    as month_3_day_13
    ,property_foreign_postal_code               as foreign_postal_code
    ,property_month_1_day_18                    as month_1_day_18
    ,property_has_the_credit_been_paid_         as has_the_credit_been_paid
    ,property_check_uploaded_by                 as check_uploaded_by
    ,property_invoice_sent_by                   as invoice_sent_by
    ,property_clear_date                        as clear_date
    ,property_customer_care_timestamp
    ,property_customer_care_sub_status
    ,created_at
    ,updated_at
    ,archived_at
    ,archived
    ,_fivetran_synced

from {{ source('hubspot_hp', 'credit') }}
