select 
   trim(customerid)                         as customerid
    ,_fivetran_deleted
    ,onetime
    ,displaycontact_mailaddress_zip
    ,deal_owner
    ,onhold
    ,cns_exclude_from_statements
    ,contactinfo_contactname
    ,shipto_visible
    ,contactinfo_printas
    ,enableonlinecardpayment
    ,split_part(offer,'.',1)                as offer
    ,partner_name
    ,cns_customer_rating
    ,whenmodified
    ,billto_visible
    ,contactinfo_phone_1
    ,displaycontact_lastname
    ,contactinfo_lastname
    ,contactinfo_mailaddress_address_1
    ,contactinfo_firstname
    ,cns_collections_contact
    ,shipto_mailaddress_zip
    ,billto_taxable
    ,cns_statements_contact
    ,billto_companyname
    ,displaycontactkey
    ,emailoptin
    ,modifiedby
    ,delivery_options
    ,name
    ,billto_printas
    ,displaycontact_mailaddress_country
    ,contactinfo_mailaddress_country
    ,cns_exclude_from_promise_to_pay
    ,displaycontact_contactname
    ,custtype
    ,recordno
    ,shipto_printas
    ,createdby
    ,billto_firstname
    ,billto_mailaddress_country
    ,displaycontact_mailaddress_state
    ,displaycontact_email_1
    ,displaycontact_status
    ,shipto_firstname
    ,shipto_contactname
    ,displaycontact_printas
    ,contactinfo_mailaddress_city
    ,displaycontact_phone_1
    ,displaycontact_mailaddress_address_1
    ,displaycontact_mailaddress_address_2
    ,advance_customer
    ,contactinfo_mailaddress_zip
    ,billto_mailaddress_address_1
    ,tax_preparer
    ,billto_mailaddress_countrycode
    ,displaycontact_taxable
    ,shipto_mailaddress_city
    ,shipto_phone_1
    ,billto_contactname
    ,contactinfo_mailaddress_countrycode
    ,shipto_mailaddress_address_1
    ,custtypekey
    ,shiptokey
    ,billto_mailaddress_city
    ,billto_phone_1
    ,shipto_lastname
    ,displaycontact_visible
    ,shipto_mailaddress_country
    ,displaycontact_url_1
    ,billto_mailaddress_state
    ,billto_mailaddress_zip
    ,contactkey
    ,contactinfo_visible
    ,displaycontact_mailaddress_countrycode
    ,contactinfo_companyname
    ,status
    ,billtokey
    ,prclst_override
    ,last_statementdate
    ,displaycontact_firstname
    ,enableonlineachpayment
    ,cns_exclude_from_auto_notices
    ,last_invoicedate
    ,whencreated
    ,totaldue
    ,shipto_taxable
    ,csc
    ,entity
    ,shipto_mailaddress_state
    ,displaycontact_companyname
    ,shipto_companyname
    ,billto_lastname
    ,shipto_mailaddress_countrycode
    ,contactinfo_mailaddress_state
    ,displaycontact_mailaddress_city
    ,_fivetran_synced
    ,hs_deal_id

 from {{ source('sage', 'customer') }} 
